#!/bin/bash

# GeoDisha Mobile Platform - Setup Script
# This script sets up the development environment

set -e

echo "🚀 Setting up GeoDisha Mobile Platform..."

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if running on macOS
if [[ "$OSTYPE" != "darwin"* ]]; then
    echo -e "${YELLOW}Warning: This script is optimized for macOS${NC}"
fi

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check Flutter installation
echo -e "\n${YELLOW}Checking Flutter installation...${NC}"
if command_exists flutter; then
    echo -e "${GREEN}✓ Flutter is installed${NC}"
    flutter --version
else
    echo -e "${RED}✗ Flutter is not installed${NC}"
    echo "Please install Flutter from: https://flutter.dev/docs/get-started/install"
    exit 1
fi

# Check Google Cloud SDK
echo -e "\n${YELLOW}Checking Google Cloud SDK...${NC}"
if command_exists gcloud; then
    echo -e "${GREEN}✓ Google Cloud SDK is installed${NC}"
    gcloud --version
else
    echo -e "${RED}✗ Google Cloud SDK is not installed${NC}"
    echo "Please install from: https://cloud.google.com/sdk/docs/install"
    exit 1
fi

# Check Python
echo -e "\n${YELLOW}Checking Python installation...${NC}"
if command_exists python3; then
    PYTHON_VERSION=$(python3 --version | cut -d' ' -f2)
    echo -e "${GREEN}✓ Python ${PYTHON_VERSION} is installed${NC}"
else
    echo -e "${RED}✗ Python 3 is not installed${NC}"
    exit 1
fi

# Check Node.js
echo -e "\n${YELLOW}Checking Node.js installation...${NC}"
if command_exists node; then
    NODE_VERSION=$(node --version)
    echo -e "${GREEN}✓ Node.js ${NODE_VERSION} is installed${NC}"
else
    echo -e "${YELLOW}! Node.js is not installed (optional for some services)${NC}"
fi

# Check Terraform
echo -e "\n${YELLOW}Checking Terraform installation...${NC}"
if command_exists terraform; then
    TERRAFORM_VERSION=$(terraform version | head -1)
    echo -e "${GREEN}✓ ${TERRAFORM_VERSION} is installed${NC}"
else
    echo -e "${YELLOW}! Terraform is not installed (optional)${NC}"
    echo "Install with: brew install terraform"
fi

# Setup Flutter project
echo -e "\n${YELLOW}Setting up Flutter project...${NC}"
cd mobile
flutter pub get
flutter pub upgrade
echo -e "${GREEN}✓ Flutter dependencies installed${NC}"
cd ..

# Create environment files
echo -e "\n${YELLOW}Creating environment configuration files...${NC}"

# Mobile app config
cat > mobile/.env << 'EOF'
# GeoDisha Mobile App Configuration
API_BASE_URL=https://api.geodisha.com
DEBUG=true
ENVIRONMENT=development
EOF

echo -e "${GREEN}✓ Created mobile/.env${NC}"

# Backend service config
mkdir -p backend/services/auth
cat > backend/services/auth/.env << 'EOF'
# Auth Service Configuration
PROJECT_ID=your-gcp-project-id
ENVIRONMENT=development
DATABASE_URL=postgresql://user:pass@localhost/geodisha
REDIS_URL=redis://localhost:6379
SECRET_KEY=change-this-in-production
EOF

echo -e "${GREEN}✓ Created backend/services/auth/.env${NC}"

# Create Firebase config template
cat > mobile/lib/core/config/firebase_options.dart << 'EOF'
// File generated by FlutterFire CLI.
// This is a template - run `flutterfire configure` to generate actual config

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'YOUR-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    storageBucket: 'YOUR-STORAGE-BUCKET',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'YOUR-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    storageBucket: 'YOUR-STORAGE-BUCKET',
    iosClientId: 'YOUR-IOS-CLIENT-ID',
    iosBundleId: 'com.geodisha.mobile',
  );
}
EOF

echo -e "${GREEN}✓ Created Firebase config template${NC}"

# Create .gitignore files
cat > .gitignore << 'EOF'
# Environment files
.env
.env.*
*.env

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Terraform
*.tfstate
*.tfstate.*
.terraform/
.terraform.lock.hcl

# Python
__pycache__/
*.py[cod]
*$py.class
venv/
ENV/

# Node
node_modules/
npm-debug.log*

# Logs
logs/
*.log
EOF

echo -e "${GREEN}✓ Created .gitignore${NC}"

# Print next steps
echo -e "\n${GREEN}✅ Setup completed successfully!${NC}"
echo -e "\n${YELLOW}Next steps:${NC}"
echo "1. Configure Firebase:"
echo "   cd mobile"
echo "   flutterfire configure"
echo ""
echo "2. Set up GCP project:"
echo "   gcloud init"
echo "   gcloud config set project YOUR_PROJECT_ID"
echo ""
echo "3. Enable required APIs:"
echo "   ./scripts/enable-gcp-apis.sh"
echo ""
echo "4. Run the mobile app:"
echo "   cd mobile"
echo "   flutter run"
echo ""
echo "5. Deploy backend services:"
echo "   cd backend/services/auth"
echo "   gcloud run deploy auth-service --source ."
echo ""
echo -e "${GREEN}For detailed instructions, see README.md${NC}"
